### PR TITLE
Documented `verbose-provider-boot` flag and linted markdown

### PR DESCRIPTION
**Pull request by djesic**
Hugo is complaining when trying to start the server locally:
```
❯ hugo server
Start building sites … 
hugo v0.107.0-2221b5b30a285d01220a26a82305906ad3291880+extended linux/amd64 BuildDate=2022-11-24T13:59:45Z VendorInfo=gohugoio
Error: Error building site: "/home/mr-computer/Workspace/documentation/content/en/docs/api/overview.md:19:1": failed to extract shortcode: template for shortcode "alert" not found
Built in 7 ms
```

Error comes from a file not edited by this PR, and I found the issue referenced online but the solutions don't work.
Could just be an issue on my machine, but wanted to mention it anyways.

### CODE REVIEW

**Review by ArneTR — COMMENTED** [review]
Information content is good!

But: Why did you rework the list indicators? I generally use a hyphen for first level, plus for second level and * for third.

This makes it way more readable when editing. What is the rationale for the change?

**Comment by djesic** [comment]
> Information content is good!
> 
> But: Why did you rework the list indicators? I generally use a hyphen for first level, plus for second level and * for third.
> 
> This makes it way more readable when editing. What is the rationale for the change?

The edit to the sublist indicators was not intended, I will revert it.

I use this Markdown linter in my IDE https://github.com/DavidAnson/markdownlint
and the sublist got falsely caught in this rule: https://github.com/DavidAnson/markdownlint/blob/main/doc/md004.md

**Comment by djesic** [comment]
I now made a configuration rule for this, so I should not reintroduce this issue

**Comment by ArneTR** [comment]
perfect!

**Pull request merged**
